### PR TITLE
Better data modal

### PR DESCRIPTION
**Pull request by aammd**
This lets users actually *use the data modal easily* which was kind of the entire point from the beginning 🤦

### CODE REVIEW

**Comment by VincentBellavance** [comment]
Is it ok if there is no chosen_region? For example with my app, I can visualize the index for the entire province or for a specific region

**Comment by aammd** [comment]
@VincentBellavance right now its a click on a region that opens the modal. So if there's no chosen_region, how would a modal show up?

**Comment by VincentBellavance** [comment]
That make a lot of sense! I was asking because in my apps, I need to press on a button to make modal appears. It could be good to eventually make a modalData function that can be used with different trigger (not for Thursday tho!)

**Comment by VincentBellavance** [comment]
But it all looks good to me!

**Pull request merged**
